kind: Deployment
apiVersion: apps/v1

metadata:
  name: mysql-deployment
  namespace: chatapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      namespace: chatapp
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
          - containerPort: 3306
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql 
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root_pass

          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql_database

          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql_user

          - name : MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password


      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc      
