kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: mysql-pvc
  namespace: chatapp

spec:
  storageClassName: standard

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

